project_id = "scjknnhoiuaregewuxws"

[functions.fetch-news]
verify_jwt = false

[functions.generate-article]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.auto-publish-articles]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.auto-internal-linking]
verify_jwt = false

[functions.process-article-tags]
verify_jwt = false

[functions.process-external-links]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.fix-missing-images]
verify_jwt = false

[functions.send-education-notification]
verify_jwt = false
